name: Deploy Blog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run deployment steps
        run: |
          echo "Creating markdown post in /posts/test-post.md"
          echo "# Test Post 🚀" > posts/test-post.md
          echo "" >> posts/test-post.md
          echo "This is a dummy post created by GitHub Actions." >> posts/test-post.md

          echo "Updating posts.json with new post info"
          if [ ! -f posts.json ]; then
            echo "[]" > posts.json
          fi
          tmpfile=$(mktemp)
          jq '. += [{"title":"Test Post 🚀","slug":"test-post","date":"2025-08-17","summary":"Created by GitHub Actions"}]' posts.json > "$tmpfile"
          mv "$tmpfile" posts.json

      - name: Commit changes
        run: |
          git add posts/test-post.md posts.json
          git commit -m "Add test post via GitHub Actions" || echo "No changes to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}